{{- if hasKey .Values.global "prometheus" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scraper-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-scraper
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus_serviceaccount_name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
