releaseName:

frontend:
  image_tag: latest
  enabled: true
  external_bridge_api_url: null
  external_bridge_api_port: null
  access_key: null
  cpus: 1
  memory: 2048Mi

bridge:
  image_tag: latest
  enabled: true
  watcher_api_url: localhost:30000
  watcher_api_key: api_key_here
  cpus: 0.35
  memory: 256Mi
