apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-{{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - name: gui-port
    port: 3000
    targetPort: 3000
  selector:
    app: {{ .Release.Name}}-{{ .Chart.Name }}