apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-{{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name}}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name}}-{{ .Chart.Name }}
    spec:
    {{ if .Values.bridge.nodeSelector }}
      nodeSelector:
      {{- range $name,$value := .Values.bridge.nodeSelector }}
        {{$name}}: {{$value}}
      {{- end }}
    {{ end }}
      containers:
      - name: bridge
        image: kalavai/kalavai-client:{{ .Values.bridge.image_tag }}
        imagePullPolicy: "IfNotPresent"
        command: ["/bin/sh", "-c"]
        args:
        - |
          python kalavai_client/bridge_api.py --host 0.0.0.0 --port 8000 --log_level debug
        ports:
        - containerPort: 8000
        env:
        - name: WATCHER_API_URL
          value: "{{ .Values.bridge.watcher_api_url }}"
        - name: WATCHER_API_KEY
          value: "{{ .Values.bridge.watcher_api_key }}"
        resources:
          requests:
            cpu: {{ .Values.bridge.cpus}}
            memory: {{ .Values.bridge.memory}}
          limits:
            cpu: {{ .Values.bridge.cpus}}
            memory: {{ .Values.bridge.memory}}
    