apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-service
  namespace: {{ .Release.Namespace }}
  {{- if .Values.bridge.labels }}
  labels:
    {{- toYaml .Values.bridge.labels | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.bridge.service.type }}
  ports:
  - name: api-main
    port: 8000
    targetPort: 8000
  selector:
    app: {{ .Release.Name}}-app